### ISSUE TITLE
Illegal group reference when encountering dollar sign in tag content

### ISSUE THREAD

**Issue by drosowski** [SmartsquareGmbH/squit#24]
Suppose we have a response XML with the following content:

```xml
...
<ErrorText>Technical error: CalculationException: An error ocurred applying tax to invoice with custom ID [CustomField1], transaction ID [fff39890-2a6d-41b7-b9b2-4ba80e0392ff]: org.springframework.web.client.HttpClientErrorException$Conflict: 409 : [There are conflicting codes for the given mapping!]</ErrorText>
...
```

The dollar sign in `HttpClientErrorException$Conflict` is interpreted as a regex group it seems, leading to
`IllegalArgumentException: Illegal group reference`

**Comment by rubengees** [comment]
I just tried but could not reproduce this. I wrote a test in which both the `response.xml` as well as the response from the server have this content but that worked. Can you post the full stacktrace and/or other relevant info that may help?

**Comment by drosowski** [comment]
If you cannot reproduce, lets close this issue for now.
